---
# Copy Inception files to remote host, build images, volumes, networks and deploy containers
# - name: Copy Inception files to remote host
#   ansible.builtin.copy:
#     src: "inception/"
#     dest: /home/ubuntu/cloud-1/
#     mode: '0755'
#     directory_mode: '0755'
#     owner: ubuntu
#     group: ubuntu

- name: Run inception
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - "images.yaml"
    - "volumes.yaml"
    - "networks.yaml"
    - "containers.yaml"