---
- name: Delete EC2 instance
  hosts: webservers
  gather_facts: false

  vars_files:
    - "./group_vars/all/env.yml"
  
  tasks:
    - name: Show WHATS IN THE FRIGGING EC2 INSTANCE
      debug:
        var: ec2_instance
  
    - name: Terminate EC2 instance
      ec2_instance:
        state: 'absent'
        instance_ids: 
        region: eu-west-3
        aws_access_key: "{{ aws_creds.ec2_access_key }}"
        aws_secret_key: "{{ aws_creds.ec2_secret_key }}"
      register: termination_result

    - name: Show termination result
      debug:
        var: termination_result

