---
- name: Provision AWS resources
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create EC2 instance
      ec2_instance:
        key_name: my-key-pair
        image_id: ami-0c94855ba95c71c99
        region: us-west-2
        instance_type: t2.micro
        wait: true
        count: 1
        instance_tags:
          Name: my-instance
      register: ec2

    - name: Print instance details
      debug:
        var: ec2.instances[0].public_ip_address