---
- hosts: ec2
  become: yes  # Run tasks with sudo privileges
  tasks:
  
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m`
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create app directory # Create application directory on remote server
      file:
        path: /src/inception
        state: directory

    - name: Copy docker-compose.yml to the server # Copy docker-compose.yml to the remote server
      copy:
        src: ./docker-compose.yml
        dest: /opt/myapp/docker-compose.yml

    - name: Run Docker Compose to deploy app # Run Docker Compose to deploy the application
      command: docker-compose up -d
      args:
        chdir: /opt/myapp
