---
# Install Docker and Docker Compose, create necessary directories, and copy inception files to the remote host
  - name: Update and install dependencies
    apt:
      update_cache: yes
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - make
        - python3
      state: present

  # - name: Add Docker GPG key
  #   apt_key:
  #     url: "{{ docker_apt_key_url }}"
  #     state: present

  # - name: Add Docker APT repository
  #   apt_repository:
  #     repo: "{{ docker_apt_repo }}"
  #     state: present

  # - name: Install Docker
  #   apt:
  #     name:
  #       - docker-ce
  #       - docker-ce-cli
  #       - containerd.io
  #     state: present

  # - name: Install Docker Compose
  #   get_url:
  #     url: "{{ docker_install_url }}"
  #     dest: /usr/local/bin/docker-compose
  #     mode: '0755'

  # - name: Add Docker to the sudo group
  #   user:
  #     name: "{{ ansible_user }}"
  #     groups: sudo
  #     append: yes

  - name: Install python dependencies
    apt:
      name: 
        - python3-boto3
        - python3-botocore
        - python3-packaging