---
# Playbook to deploy Inception
- name: Deploy Inception
  hosts: all
  become: true
  # gather_facts: true  # Gather system information

  vars_files:
  - "../group_vars/all/env-inception.yml"  # Load environment variables

  roles:
    - role: inception