# Playbook to provision EC2 instance on AWS
---
- name: Provision EC2 Instance on AWS
  hosts: localhost
  gather_facts: false
  # become: true # Run tasks with root privileges

  vars_files:
    - "../group_vars/all/env.yml"  # Load environment variables

  roles:
    - role: aws_ec2
      vars:
        ec2_name: cloud-1
        region: eu-west-3
        key_name: aws_cloud1_keypair  # Key name for SSH
        key_file_path: "../{{ key_name }}"  # Path to store the private key locally
        image: ami-04a92520784b93e73  # Ubuntu 24.04 LTS AMI
        instance_type: t2.micro
        sec_group: "cloud1-group"
        hosts_ini_file: "../inventory/hosts.ini"
