---
- name: Reboot all EC2 instances
  hosts: localhost
  gather_facts: false
  # become: true

  vars_files:
    - "../group_vars/all/env.yml"

  tasks:
    - name: Get EC2 instance facts
      amazon.aws.ec2_instance_info:
        region: eu-west-3
        filters:
          instance-state-name: ["running"]
        aws_access_key: "{{ aws_creds.ec2_access_key }}"
        aws_secret_key: "{{ aws_creds.ec2_secret_key }}"
      register: ec2_instances

    - name: Reboot EC2 instance
      amazon.aws.ec2_instance:
        region: eu-west-3
        state: restarted
        instance_ids: "{{ item.instance_id }}"
        aws_access_key: "{{ aws_creds.ec2_access_key }}"
        aws_secret_key: "{{ aws_creds.ec2_secret_key }}"
        wait: true
        wait_timeout: 300
      loop: "{{ ec2_instances.instances }}"
      when: item.instance_id is defined

