---
- name: Remove host entry from hosts.ini
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Remove all host entries under [webservers] from hosts.ini
      lineinfile:
        path: ../inventory/hosts.ini
        regexp: '^server_.*'
        state: absent
      when: "'[webservers]' in lookup('file', '../inventory/hosts.ini')"
